/** Hand-maintained OpenAPI 3.1 summary of the /api/v1 surface (§8). */
export const openApiSpec = {
  openapi: '3.1.0',
  info: { title: 'WorkLink API', version: '1.0.0', description: 'Manual-work marketplace API' },
  servers: [{ url: '/api/v1' }],
  components: {
    securitySchemes: {
      bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
      refreshCookie: { type: 'apiKey', in: 'cookie', name: 'wl_rt' },
    },
    schemas: {
      Error: {
        type: 'object',
        properties: { error: { type: 'object', properties: { code: { type: 'string' }, message: { type: 'string' }, details: {} } } },
      },
      ListEnvelope: {
        type: 'object',
        properties: { data: { type: 'array', items: {} }, meta: { type: 'object', properties: { nextCursor: { type: ['string', 'null'] } } } },
      },
    },
  },
  paths: {
    '/health': { get: { summary: 'Health check', responses: { 200: { description: 'ok' } } } },
    '/auth/signup': { post: { summary: 'Create account, receive OTP challenge', responses: { 201: { description: 'Created' }, 409: { description: 'Account exists' } } } },
    '/auth/verify-otp': { post: { summary: 'Verify OTP → session (access token + refresh cookie)', responses: { 200: { description: 'Session' } } } },
    '/auth/resend-otp': { post: { summary: 'Resend OTP (max 3/hour)', responses: { 200: { description: 'New challenge' } } } },
    '/auth/login': { post: { summary: 'Password login', responses: { 200: { description: 'Session' }, 401: { description: 'Invalid credentials' } } } },
    '/auth/refresh': { post: { summary: 'Rotate refresh token (reuse detection)', responses: { 200: { description: 'New session' } } } },
    '/auth/logout': { post: { summary: 'Revoke current session', responses: { 200: { description: 'ok' } } } },
    '/auth/logout-all': { post: { summary: 'Revoke all sessions', responses: { 200: { description: 'ok' } } } },
    '/auth/forgot-password': { post: { summary: 'Request password-reset OTP (no enumeration)', responses: { 200: { description: 'Challenge' } } } },
    '/auth/reset-password': { post: { summary: 'Reset password with OTP; invalidates sessions', responses: { 200: { description: 'ok' } } } },
    '/users/me': {
      get: { summary: 'Current user + profile + settings', responses: { 200: { description: 'SelfUser' } } },
      patch: { summary: 'Update profile', responses: { 200: { description: 'SelfUser' } } },
    },
    '/users/me/settings': { patch: { summary: 'Update settings (theme/language/currency/notifications/privacy)', responses: { 200: { description: 'UserSettings' } } } },
    '/users/me/password': { post: { summary: 'Change password (revokes sessions)', responses: { 200: { description: 'ok' } } } },
    '/users/me/deactivate': { post: { summary: 'Soft-delete account (30-day purge)', responses: { 200: { description: 'ok' } } } },
    '/users/{id}': { get: { summary: 'Public profile', responses: { 200: { description: 'PublicProfile' }, 404: { description: 'Not found' } } } },
    '/users/{id}/reviews': { get: { summary: 'Published reviews for a user', responses: { 200: { description: 'ReviewView[]' } } } },
    '/jobs': {
      post: { summary: 'Create job (publish or autosave draft)', responses: { 201: { description: 'JobDetail' } } },
      get: { summary: 'Search jobs (q, lat/lng/radiusKm, category, payType, minPay/maxPay, startAfter, cursor)', responses: { 200: { description: 'JobSummary[]' } } },
    },
    '/jobs/{id}': {
      get: { summary: 'Job detail with viewer relationship', responses: { 200: { description: 'JobDetail' } } },
      patch: { summary: 'Update own job', responses: { 200: { description: 'JobDetail' } } },
    },
    '/jobs/{id}/close': { post: { summary: 'Close own post', responses: { 200: { description: 'JobDetail' } } } },
    '/jobs/{id}/apply': { post: { summary: 'Apply to a job', responses: { 201: { description: 'Application' }, 409: { description: 'Already applied / closed' } } } },
    '/jobs/{id}/applications': { get: { summary: 'List applications (employer only)', responses: { 200: { description: 'ApplicationView[]' } } } },
    '/jobs/{id}/save': { post: { summary: 'Toggle save', responses: { 200: { description: '{ saved }' } } } },
    '/feed': { get: { summary: 'Ranked feed (tab=nearby|matched|all, cursor)', responses: { 200: { description: 'FeedResponse' } } } },
    '/me/jobs': { get: { summary: 'Employer: my posts', responses: { 200: { description: 'JobSummary[]' } } } },
    '/me/applications': { get: { summary: 'Worker: my applications', responses: { 200: { description: 'WorkerApplicationView[]' } } } },
    '/applications/{id}': { patch: { summary: 'shortlist|accept|reject|withdraw', responses: { 200: { description: 'Status' } } } },
    '/me/assignments': { get: { summary: 'My assignments (both roles)', responses: { 200: { description: 'AssignmentView[]' } } } },
    '/assignments/{id}/logs': { post: { summary: 'Worker submits day/hour log', responses: { 201: { description: 'DayLog' } } } },
    '/assignments/{id}/logs/{logId}/decision': { post: { summary: 'Employer approves/rejects log', responses: { 200: { description: 'DayLog' } } } },
    '/assignments/{id}/complete': { post: { summary: 'Mark work complete', responses: { 200: { description: 'AssignmentView' } } } },
    '/assignments/{id}/reviews': { post: { summary: 'Submit review (double-blind, reveals on mutual or 7d)', responses: { 201: { description: 'ReviewView' } } } },
    '/assignments/{id}/review-state': { get: { summary: 'Whether viewer/other submitted', responses: { 200: { description: 'ReviewState' } } } },
    '/search/jobs': { get: { summary: 'Full-text + fuzzy job search with filters', responses: { 200: { description: 'JobSummary[]' } } } },
    '/search/people': { get: { summary: 'People search (name/skill/location, rating filter)', responses: { 200: { description: 'PublicProfile[]' } } } },
    '/conversations': {
      get: { summary: 'My conversations with unread counts', responses: { 200: { description: 'ConversationView[]' } } },
      post: { summary: 'Get or create conversation for (job, peer)', responses: { 201: { description: '{ id }' } } },
    },
    '/conversations/{id}/messages': {
      get: { summary: 'Cursor-paginated messages', responses: { 200: { description: 'MessageView[]' } } },
      post: { summary: 'Send message (text and/or image attachments)', responses: { 201: { description: 'MessageView' } } },
    },
    '/conversations/{id}/read': { post: { summary: 'Mark read', responses: { 200: { description: 'ok' } } } },
    '/notifications': { get: { summary: 'In-app notification center', responses: { 200: { description: 'NotificationView[]' } } } },
    '/notifications/read': { post: { summary: 'Mark read (ids or all)', responses: { 200: { description: 'ok' } } } },
    '/devices': { post: { summary: 'Register Web Push subscription', responses: { 200: { description: 'ok' } } } },
    '/uploads/presign': { post: { summary: 'Presigned upload (MIME/size validated)', responses: { 200: { description: 'PresignResult' } } } },
    '/uploads/confirm': { post: { summary: 'Confirm upload → public URL', responses: { 200: { description: '{ url }' } } } },
    '/reports': { post: { summary: 'Report user/job/message', responses: { 201: { description: 'Report' } } } },
    '/blocks': { post: { summary: 'Block a user', responses: { 200: { description: 'ok' } } } },
    '/payments/config': { get: { summary: 'Payments feature flag + provider', responses: { 200: { description: 'config' } } } },
    '/payments/intent': { post: { summary: 'Create escrow funding intent (idempotent)', responses: { 201: { description: 'Payment + checkout' } } } },
    '/payments/{id}/capture': { post: { summary: 'Capture funds into escrow', responses: { 200: { description: 'Payment' } } } },
    '/payments/{id}/release': { post: { summary: 'Release (partial or full) to worker', responses: { 200: { description: 'Payment' } } } },
    '/payments/{id}/refund': { post: { summary: 'Refund escrow to employer', responses: { 200: { description: 'Payment' } } } },
    '/webhooks/{provider}': { post: { summary: 'Signed gateway webhook (replay-protected)', responses: { 200: { description: 'received' } } } },
    '/me/earnings': { get: { summary: 'Earnings dashboard (ledger-backed)', responses: { 200: { description: 'Earnings' } } } },
    '/admin/reports': { get: { summary: 'Moderation queue (admin)', responses: { 200: { description: 'ReportView[]' } } } },
    '/admin/reports/{id}/decision': { post: { summary: 'Dismiss or take action (admin)', responses: { 200: { description: 'Report' } } } },
    '/admin/users/{id}/status': { post: { summary: 'Suspend / shadow-ban / reactivate (admin)', responses: { 200: { description: 'User' } } } },
    // WS events (Socket.IO): message:new, message:read, typing, notification:new, job:new
  },
} as const;
